extends Node
## WordDB — runtime word lookup, backed by JSON files bundled in res://data/.
##
## Loaded once at app startup; queries are O(1) for guess validation
## (HashSet lookup) and O(daily_pool_size) for daily seed selection (the
## daily query is ~once per day per language, so no caching needed).
##
## Both JSON files were generated by scripts/phase0_curate_*.py from
## frequency-ranked corpus analysis. See research/word_db_sourcing.md
## for the legal-clearance rationale and provenance.

# Loaded data: per-language daily-pool (filtered by tier) and full guess pool
var _daily_pools: Dictionary = {}  # {lang: {tier: Array[Dictionary]}}
var _guess_sets: Dictionary = {}   # {lang: HashSet of valid words}
var _loaded: bool = false


func _ready() -> void:
	_load("hi", "res://data/words_hi.json")
	_load("en", "res://data/words_en.json")
	_loaded = true
	print("WordDB ready: hi=%d guesses, en=%d guesses" % [
		_guess_sets["hi"].size(),
		_guess_sets["en"].size(),
	])


func _load(lang: String, path: String) -> void:
	if not FileAccess.file_exists(path):
		push_error("WordDB: missing %s" % path)
		return

	var f: FileAccess = FileAccess.open(path, FileAccess.READ)
	var content: String = f.get_as_text()
	f.close()

	var entries: Variant = JSON.parse_string(content)
	if entries == null or not entries is Array:
		push_error("WordDB: invalid JSON at %s" % path)
		return

	# Build daily pool by tier
	var tiered: Dictionary = {"common": [], "mid": [], "challenge": []}
	var guess_set: Dictionary = {}  # used as HashSet (key presence)

	for e in entries:
		# Build guess set from in_guess_pool entries
		if e.get("in_guess_pool", 0) == 1:
			guess_set[e["word"]] = true
		# Build daily pools
		if e.get("in_daily_pool", 0) == 1:
			var tier: String = e.get("tier", "common")
			if tiered.has(tier):
				tiered[tier].append(e)

	_daily_pools[lang] = tiered
	_guess_sets[lang] = guess_set


## Returns daily-pool entries for the given (lang, tier), already sorted by
## frequency_rank ascending (most common first).
func get_daily_pool(lang: String, tier: String) -> Array:
	if not _daily_pools.has(lang):
		return []
	return _daily_pools[lang].get(tier, [])


## True if the input word is in the lang-specific guess pool.
## Caller normalizes (lowercase for en, strip whitespace for hi).
func is_valid_guess(word: String, lang: String) -> bool:
	if not _guess_sets.has(lang):
		return false
	return _guess_sets[lang].has(word)


## Total guess-pool size for a language (used for diagnostics).
func guess_pool_size(lang: String) -> int:
	if not _guess_sets.has(lang):
		return 0
	return _guess_sets[lang].size()


## True if WordDB finished loading.
func is_loaded() -> bool:
	return _loaded
